name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm
      - name: Cache PureScript dependencies
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('spago.yaml', 'spago.lock', 'package-lock.json') }}
          path: |
            .spago
      - name: Install dependencies
        run: npm ci

      - name: Build source
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Check formatting
        run: npm run check
